### ISSUE TITLE
Import error with scrublet.py in the htapp_method_lungs

### ISSUE THREAD

**Issue by liliay** [klarman-cell-observatory/HTAPP-Pipelines#1]
Hi there, 

First of all thank you for sharing you work and scripts with us, it is very helpful. 
My project is to recreate the very complete QC pipeline shared in the paper : https://www.nature.com/articles/s41591-020-0844-1 
I am working on a single sample and trying to first identify the big steps that are of interest for my lab project. 
I am facing an issue when it comes to running scrublet. 
Here are the few lines that pose a problem : 
source_python(paste0(proj.path, "/src/scrublet.py"))
for (i in seq(sampleid)) {
  run_scrublet(sampleid[i], sparse.dir[i], figures.pythondir)
}
And here is the error I get : 
Error in py_run_file_impl(file, local, convert) : ImportError: attempted relative import with no known parent package

In the initial script scrublet is run through this script : "/src/scrublet_function_GTEx.py"

I got my file scrublet.py by downloading the scrublet repository. 
Is your scrublet_function_GTEx.py still available somewhere ? 

Thanks in advance for your reply, 

Lilia

**Comment by orrzor** [comment]
Hi Lilia,

I am glad the scripts have been helpful. I just uploaded a function `scrublet_function.py`, which I had forgotten to include. Thanks for spotting this. It basically runs `scrublet` from within R. I will just remind you that setting the threshold for doublets (using the doublet score) is not completely automatic and you should set this based on your knowledge of the experiment and the biology. Best, Orr

**Comment by liliay** [comment]
Thank you so much for the update !
